// lib/constants.ts
// Keyword sets used by the heuristic extractor.
// Kept here (not in schema.ts) so schema stays a pure type/validation module.

export const ACTION_TRIGGERS: readonly string[] = [
  "must",
  "shall",
  "should",
  "required to",
  "required",
  "need to",
  "needs to",
  "prohibited",
  "forbidden",
  "not allowed",
  "mandatory",
  "responsible for",
  "ensure",
  "responsible to",
];

export const DUE_PATTERNS: readonly RegExp[] = [
  /\bwithin\s+\d+\s*(?:minute|minutes|min|hour|hours|hr|hrs|day|days|week|weeks|month|months)\b/i,
  /\bby\s+(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday|end of (?:day|week|month|quarter|year)|noon|eod|cob|close of business|next (?:day|week|month))\b/i,
  /\bbefore\s+[a-z][\w\s-]{2,40}/i,
  /\bafter\s+[a-z][\w\s-]{2,40}/i,
  /\bevery\s+(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday|day|week|month|quarter|hour|6 hours|12 hours|24 hours|\d+\s*(?:min|minutes|hours|hrs|days))\b/i,
  /\bon\s+(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i,
  /\bby\s+\d{1,2}(?::\d{2})?\s*(?:am|pm|h)?\b/i,
  /\bat\s+\d{1,2}(?::\d{2})?\s*(?:am|pm)?\b/i,
  /\bno later than\b/i,
  /\bimmediately\b/i,
  /\basap\b/i,
];

export const OWNER_KEYWORDS: readonly string[] = [
  "it",
  "security team",
  "security",
  "requestor",
  "system owner",
  "owner",
  "vendor",
  "dpo",
  "data protection officer",
  "hr",
  "human resources",
  "legal",
  "compliance",
  "finance",
  "manager",
  "supervisor",
  "admin",
  "administrator",
  "developer",
  "devops",
  "sre",
  "support",
  "helpdesk",
  "engineer",
  "analyst",
  "team lead",
  "lead",
  "employee",
  "staff",
  "user",
  "customer",
  "client",
  "auditor",
  "reviewer",
  "approver",
];

export const RISK_TRIGGERS: readonly string[] = [
  "risk",
  "threat",
  "vulnerability",
  "breach",
  "leak",
  "exposure",
  "non-compliance",
  "noncompliance",
  "violation",
  "penalty",
  "fine",
  "lawsuit",
  "legal action",
  "downtime",
  "outage",
  "data loss",
  "loss of access",
  "security incident",
  "compromise",
  "unauthorized",
  "fraud",
  "phishing",
  "malware",
  "ransomware",
  "attack",
];

export const OBLIGATION_TRIGGERS: readonly string[] = [
  "must",
  "shall",
  "required to",
  "required",
  "is required",
  "are required",
  "mandatory",
  "obligated to",
  "expected to",
];

export const HIGH_PRIORITY_TRIGGERS: readonly string[] = [
  "security",
  "breach",
  "incident",
  "critical",
  "urgent",
  "immediate",
  "immediately",
  "asap",
  "lawsuit",
  "penalty",
  "fine",
  "regulator",
  "audit",
  "compromise",
  "unauthorized",
  "data loss",
  "ransomware",
  "outage",
  "downtime",
  "within 24 hours",
  "within 1 hour",
  "same day",
];

export const LOW_PRIORITY_TRIGGERS: readonly string[] = [
  "consider",
  "recommended",
  "nice to have",
  "optional",
  "best practice",
  "guideline",
  "should consider",
  "may",
  "could",
  "when possible",
];
