// lib/markdown.ts — Extracted JSON → Markdown string.
import type { Extracted } from "./types";

const priorityEmoji: Record<string, string> = {
  urgent: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🟢",
};

const severityEmoji: Record<string, string> = {
  high: "🔴",
  medium: "🟡",
  low: "🟢",
};

function actionLine(a: Extracted["actions"][number]): string {
  const parts: string[] = [`- [ ] **${a.action}**`];
  const meta: string[] = [];
  if (a.owner) meta.push(`Owner: ${a.owner}`);
  if (a.due) meta.push(`Due: ${a.due}`);
  meta.push(`Priority: ${a.priority}`);
  parts.push(`  ${meta.join(" · ")}`);
  return parts.join("\n");
}

export function toMarkdown(r: Extracted): string {
  const lines: string[] = [];
  lines.push("# ActionLens Report");
  lines.push("");
  lines.push(`_Generated: ${new Date().toISOString()}_`);
  lines.push("");

  lines.push("## ✅ Action Items");
  if (r.actions.length === 0) lines.push("_None identified._");
  else lines.push(r.actions.map(actionLine).join("\n"));
  lines.push("");

  lines.push("## 📌 Key Obligations");
  if (r.obligations.length === 0) lines.push("_None identified._");
  else lines.push(r.obligations.map((o) => `- ${o}`).join("\n"));
  lines.push("");

  lines.push("## ⚠️ Risks & Consequences");
  if (r.risks.length === 0) lines.push("_None identified._");
  else
    lines.push(
      r.risks
        .map((rk) => `- ${severityEmoji[rk.severity] ?? "•"} **${rk.severity.toUpperCase()}** — ${rk.text}`)
        .join("\n")
    );
  lines.push("");

  lines.push("## ❓ Open Questions");
  if (r.questions.length === 0) lines.push("_None identified._");
  else lines.push(r.questions.map((q) => `- ${q}`).join("\n"));
  lines.push("");

  lines.push("## 🧭 Summary");
  if (r.summary.length === 0) lines.push("_No summary available._");
  else lines.push(r.summary.map((s) => `- ${s}`).join("\n"));
  lines.push("");

  lines.push("---");
  lines.push("_Generated by ActionLens. Heuristic extraction; review before use._");
  return lines.join("\n");
}
